addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.5.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"             % "0.10.0")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"            % "1.5.5")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("ch.epfl.lamp"       % "sbt-dotty"                 % "0.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"              % "0.9.25")
