addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.10.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.2.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"             % "0.11.0")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"            % "1.5.10")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"              % "0.10.0")
