name: CI

on:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        java: ['openjdk@1.17.0']
        scala: ['2.11.12', '2.12.16', '2.13.11', "3.2.1"]
        platform: ['JVM', 'JS']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v5
      - name: Run tests
        if: matrix.scala != '3.2.1'
        run: sbt ++${{ matrix.scala }}! test${{ matrix.platform }}
      - name: Run dotty tests
        if: matrix.scala == '3.2.1' && matrix.platform == 'JVM'
        run: sbt ++${{ matrix.scala }}! testJVM

  publish:
    runs-on: ubuntu-20.04
    needs: [test]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Scala and Java 
        uses: olafurpg/setup-scala@v14
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
